### ISSUE TITLE
Title suffix is gone if restricted user save the page properties

### ISSUE THREAD

**Issue by glucka** [t3brightside/advancedtitle#2]
Any idea why is this happen?
Typo3 v10, v11

**Comment by t3brightside** [comment]
Not quite sure now, does it function fine as long as the user has the field enabled?

**Comment by glucka** [comment]
I tested now again, with root user the same thing. I see the suffix only after clearing the entire cache. After save the page-properties -> suffix is gone again.

**Comment by t3brightside** [comment]
Oh, now I remember having an issue with after changing the rootline fields setup, but should be fixed again in latest version. Using the latest 1.2.1?

**Comment by glucka** [comment]
With v1.2.1 works perfect! Thank you!

**Comment by t3brightside** [comment]
Cool, thanks for the feedback!
